---
- name: Packer Build Playbook
  hosts: default
  become: true

  collections:
    - firstfloor.general
    - devsec.hardening

  pre_tasks:
    - name: Upgrade Packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
    
    - name: Reboot after Upgrade
      ansible.builtin.reboot:

  roles:
    - firstfloor.general.user
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
